### ISSUE TITLE
[3pt] Explore graal native image generation

### ISSUE THREAD

**Issue by scasplte2** [Topl/Prosomo#44]
For RC5 we would like to make it as easy as possible for people to join and leave the network

**Comment by aaronschutza** [comment]
The simulation and testnet UI are ready to be deployed using a native image (simple executable that doen't require java to be preinstalled).  We will have releases for linux/mac/windows that users will be able to run on their desktop or a terminal.  The UI will be used by most participants for managing keys and transactions.

**Comment by aaronschutza** [comment]
Some info on the current state of native image:
https://dzone.com/articles/profiling-native-images-in-java

**Comment by aaronschutza** [comment]
The open issue on graalvm regarding java AWT support:
https://github.com/oracle/graal/issues/1327

**Comment by aaronschutza** [comment]
I got all the tooling for native image working and found out that graphics aren't supported.  It seems there is not much benefit to native image for now and it would only run in headless mode even if we got it working with AWT.  Graphics support may not come for years as it is not high on their list of priorities.  Native image is more suited to smaller java backend applications that have to restart a lot very quickly.  I'm not seeing much benefit besides not having a JVM installed to run it, I'm not entirely certain that it will play nice with an app as large as prosomo/bifrost memory wise as it is still experimental.  We will have to release as a fatjar and a JDK will have to be installed in order to run the jar.
